In [17]:
# ============================================================
# IMPORTAÇÃO DE BIBLIOTECA
# ============================================================

import pandas as pd


# ============================================================
# CARREGAMENTO DOS DADOS (EXTRACT)
# ============================================================

# Caminho do arquivo Excel
arquivo = "../dados_bruto/EVENTOS.xlsx"

# Leitura das planilhas
events = pd.read_excel(arquivo, sheet_name="events")
emp = pd.read_excel(arquivo, sheet_name="EMP")
cat = pd.read_excel(arquivo, sheet_name="Cat_Events")

In [18]:
# Visualizar dados brutos
display(events)
display(emp)
display(cat)

,data_evnt,id_empresa,tipo_eventos,PGTO,TOTAL DE PART. EVENTO,COBERTURA,COORDENADOR RESP,valor faturado do dia,20% Royalties Holding,2% desc p/ Contratante,Contratante,Categoria
0,2017-01-02,15,Fórum de Tecnologia,50% PAGO,1268,Daily Chronicle,Marcelo Mendes,102150.0,20430.000,2043.00,Johnson Enterprises,402
1,2017-01-02,20,Fórum de Tecnologia,50% PAGO,299,News Wave,Natalia Silva,108310.0,16246.500,0.00,Coleman Holdings,401
2,2017-01-03,2,Competição Esportiva,50% PAGO,1136,The Urban Tribune,Vilma Soares,113362.5,17004.375,2267.25,Não Cadastrado,400
3,2017-01-03,19,Competição Esportiva,SIM,328,City Newsline,Geraldo Pereira,109048.0,16357.200,0.00,Coleman Holdings,401
4,2017-01-04,12,Fórum de Tecnologia,NÃO,392,City Newsline,Geraldo Pereira,NaN,0.000,0.00,Reed Corporation,401
...,...,...,...,...,...,...,...,...,...,...,...,...
451,2017-05-16,6,Desfile de Moda,50% PAGO,438,Urban Herald,Natalia Silva,283081.0,42462.150,5661.62,Foster Corporation,402
452,2017-05-16,18,Congresso Científico,SIM,1307,The Urban Tribune,Marcelo Mendes,262595.0,39389.250,5251.90,Mitchell Enterprises,400
453,2017-05-16,4,Congresso Científico,SIM,1232,City News Now,Geraldo Pereira,217683.0,32652.450,0.00,Roberts Partners,401
454,2017-05-16,14,Seminário de Desenvolvimento Pessoal,NÃO,1125,Express News,Vilma Soares,NaN,0.000,0.00,Davis Holdings,400
455,2017-03-30,19,Encontro de Networking,NÃO,449,Metro Messenger,Vilma Soares,NaN,0.000,0.00,Coleman Holdings,403

    SKU                     EMP  TOTAL DE FUNC
0     1            Dream Events            334
1     2     Stellar Productions            452
2     3         Elite Occasions            153
3     4       Enchanted Affairs            220
4     5          Spectra Events            534
5     6      Fusion Experiences            347
6     7  Grand Gala Productions            437
7     8         Magical Moments            211
8     9   Prestige Celebrations            139
9    10         Euphoria Events            484
10   11       Opulent Occasions            221
11   12     Blissful Gatherings            537
12   13    Radiant Celebrations            222
13   14        Majestic Affairs            548
14   15     Sparkle Productions            578
15   16          Harmony Events            139
16   17    Celebrate Excellence            172
17   18      Imagination Events            339
18   19     Jubilee Enterprises            187
19   20   Aether Event Planning            539

   SKU                Cat        Visão
0  400             ABERTO  Custo baixo
1  401            FECHADO  Custo baixo
2  402  VENDA SOB DEMANDA   Custo Alto
3  403         CONVIDADOS   Custo Alto

In [19]:
# ============================================================
# EXPLORAÇÃO INICIAL DOS DADOS (EDA)
# ============================================================

# Ver estrutura das tabelas (tipos, nulos, colunas)
display(events.info())
display(emp.info())
display(cat.info())

<class 'pandas.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   data_evnt               456 non-null    str
 1   id_empresa              456 non-null    int64
 2   tipo_eventos            456 non-null    str
 3   PGTO                    456 non-null    str
 4   TOTAL DE PART. EVENTO   456 non-null    int64
 5   COBERTURA               456 non-null    str
 6   COORDENADOR RESP        456 non-null    str
 7   valor faturado do dia   338 non-null    float64
 8   20% Royalties Holding   456 non-null    float64
 9   2% desc p/ Contratante  456 non-null    float64
 10  Contratante             456 non-null    str
 11  Categoria               456 non-null    int64
dtypes: float64(3), int64(3), str(6)
memory usage: 42.9 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SKU            20 non-null     int64
 1   EMP            20 non-null     str
 2   TOTAL DE FUNC  20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

None

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SKU     4 non-null      int64
 1   Cat     4 non-null      str
 2   Visão   4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

None

In [20]:
# ============================================================
# TRATAMENTO DOS DADOS (TRANSFORM)
# ============================================================

# ---------- 1. Converter coluna de data ----------
# Transformar a coluna de string para formato datetime
events["data_evnt"] = pd.to_datetime(events["data_evnt"])

In [22]:
# ---------- 2. Padronizar nomes das colunas ----------
# Renomear colunas para facilitar análise e uso em SQL/Power BI
events.columns = [
    "data_evento",
    "id_empresa",
    "tipo_evento",
    "pagamento",
    "total_participantes",
    "cobertura",
    "coordenador",
    "valor_faturado",
    "royalties",
    "desconto_contratante",
    "contratante",
    "categoria"
]

emp.columns = [
"id_empresa",
"empresa",
"total_funcionarios"
]

cat.columns = [
"id_categoria",
"categoria",
"visao"
]
# Conferir estrutura após ajuste
# ============================================================
display(events.info())
display(emp.info())
display(cat.info())

<class 'pandas.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   data_evento           456 non-null    datetime64[us]
 1   id_empresa            456 non-null    int64
 2   tipo_evento           456 non-null    str
 3   pagamento             456 non-null    str
 4   total_participantes   456 non-null    int64
 5   cobertura             456 non-null    str
 6   coordenador           456 non-null    str
 7   valor_faturado        338 non-null    float64
 8   royalties             456 non-null    float64
 9   desconto_contratante  456 non-null    float64
 10  contratante           456 non-null    str
 11  categoria             456 non-null    int64
dtypes: datetime64[us](1), float64(3), int64(3), str(5)
memory usage: 42.9 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_empresa          20 non-null     int64
 1   empresa             20 non-null     str
 2   total_funcionarios  20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

None

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_categoria  4 non-null      int64
 1   categoria     4 non-null      str
 2   visao         4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

None

In [9]:
# ---------- 3. Tratamento de valores nulos ----------
# Verificar quantidade de valores nulos na coluna de faturamento
events["valor_faturado"].isnull().sum()

# Criar coluna indicando se o evento é gratuito
# True = evento sem faturamento (gratuito)
# False = evento com faturamento (pago)
events["evento_gratuito"] = events["valor_faturado"].isnull()

# Substituir valores nulos por 0 para permitir cálculos
events["valor_faturado"] = events["valor_faturado"].fillna(0)


# ============================================================
# RESULTADO FINAL (LOAD)
# ============================================================

# Visualizar base tratada
display(events)

,data_evento,id_empresa,tipo_evento,pagamento,total_participantes,cobertura,coordenador,valor_faturado,royalties,desconto_contratante,contratante,categoria,evento_gratuito
0,2017-01-02,15,Fórum de Tecnologia,50% PAGO,1268,Daily Chronicle,Marcelo Mendes,102150.0,20430.000,2043.00,Johnson Enterprises,402,False
1,2017-01-02,20,Fórum de Tecnologia,50% PAGO,299,News Wave,Natalia Silva,108310.0,16246.500,0.00,Coleman Holdings,401,False
2,2017-01-03,2,Competição Esportiva,50% PAGO,1136,The Urban Tribune,Vilma Soares,113362.5,17004.375,2267.25,Não Cadastrado,400,False
3,2017-01-03,19,Competição Esportiva,SIM,328,City Newsline,Geraldo Pereira,109048.0,16357.200,0.00,Coleman Holdings,401,False
4,2017-01-04,12,Fórum de Tecnologia,NÃO,392,City Newsline,Geraldo Pereira,0.0,0.000,0.00,Reed Corporation,401,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,2017-05-16,6,Desfile de Moda,50% PAGO,438,Urban Herald,Natalia Silva,283081.0,42462.150,5661.62,Foster Corporation,402,False
452,2017-05-16,18,Congresso Científico,SIM,1307,The Urban Tribune,Marcelo Mendes,262595.0,39389.250,5251.90,Mitchell Enterprises,400,False
453,2017-05-16,4,Congresso Científico,SIM,1232,City News Now,Geraldo Pereira,217683.0,32652.450,0.00,Roberts Partners,401,False
454,2017-05-16,14,Seminário de Desenvolvimento Pessoal,NÃO,1125,Express News,Vilma Soares,0.0,0.000,0.00,Davis Holdings,400,True
455,2017-03-30,19,Encontro de Networking,NÃO,449,Metro Messenger,Vilma Soares,0.0,0.000,0.00,Coleman Holdings,403,True

In [31]:
events.to_csv("../dados_tratados/events.csv", index=False)
emp.to_csv("../dados_tratados/empresas.csv", index=False)
cat.to_csv("../dados_tratados/categorias.csv", index=False)

In [30]:
import os

os.makedirs("../dados_tratados", exist_ok=True)
print("Pasta criada com sucesso!")

Pasta criada com sucesso!

In [15]:
# Regra de negócio:
# Eventos sem valor faturado são considerados eventos gratuitos

#INSIGHTS
#Insight 1 - Alto número de eventos gratuitos
#nsight 2 - Concentração de receita em poucos eventos
#Insight 3 - Relação direta entre participantes e faturamento
#Insight 4 - Diferença de performance entre categorias
#Insight 5 - Empresas com maior volume de eventos